/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "API-V1": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "API_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ARBITRUM_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BASE_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BETTER_AUTH_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "CELO_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DEBRIDGE_API": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ENCRYPTION_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ETH_SEPOLIA_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GASLESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GNOSIS_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IDENTITY_STRIPE_API": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IDENTITY_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "IdentityWebhook": {
      "id": string
      "secret": string
      "type": "stripe.index/webhookEndpoint.WebhookEndpoint"
    }
    "InternalEventBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "LandingPageNormieTech": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "NEXT_PUBLIC_POSTHOG_HOST": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NEXT_PUBLIC_POSTHOG_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "OP_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "POLYGON_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PaymentWebhookForId": {
      "id": string
      "secret": string
      "type": "stripe.index/webhookEndpoint.WebhookEndpoint"
    }
    "RESEND_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "RESERVE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SOLANA_DEV_NET_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SOLANA_GASLESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SOLANA_RESERVE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SOLANA_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SQUARE_AUTH_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "SQUARE_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TRON_GASLESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TRON_NILE_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TRON_RESERVE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "TRON_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WebhookEventBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
  }
}
