/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ARBITRUM_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "BASE_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GASLESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LandingPageNormieTech": {
      "type": "sst.aws.Nextjs"
      "url": string
    }
    "Normie-Tech-API-V1": {
      "type": "sst.aws.ApiGatewayV1"
      "url": string
    }
    "OP_RPC_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "PaymentWebhookForId": {
      "id": string
      "secret": string
      "type": "stripe.index/webhookEndpoint.WebhookEndpoint"
    }
    "RESERVE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
